'use client'

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import Head from "next/head";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";
import { BentoEditorProvider } from "@/providers/BentoEditorMode";
import { LayoutManagerProvider } from "@/providers/LayoutManager";
import { AuthProvider } from "@/providers/AuthProvider";


export default function RootLayout({ children }) {


    return (
        <>
            <div>
                <AuthProvider>
                    <LayoutManagerProvider>
                        <BentoEditorProvider>
                            <Header />
                            <Sidebar />
                            {children}
                        </BentoEditorProvider>
                    </LayoutManagerProvider>
                </AuthProvider>
            </div>
        </>
    );
}



