import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { SessionProvider } from "next-auth/react";
import { getServerSession } from "next-auth";
import AuthProvider from "@/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {

  const session = await getServerSession()

  return (
    <html lang="en">
      <AuthProvider>

        <body className={inter.className}>{children}</body>
      </AuthProvider>
      <Toaster />

    </html>
  );
}
